language: python

before_install:
  - sudo apt-get update
  - sudo apt-get install git build-essential nodejs
  - tests/cjdns.sh
  - pip install tox

script: tox
env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py32
  - TOXENV=py33
  - TOXENV=py34

notifications:
  webhooks: http://webhooks.meshwith.me:8080/webhooks/
